name: Build and Deploy to Production

on:
  push:
    branches:
      - 'production'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish application
        run: dotnet publish -c Release -o ./publish

      - name: Create zip file
        run: zip -r ./publish.zip ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish-artifact
          path: ./publish.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: publish-artifact

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy to Azure Web App
        run: az webapp deploy --resource-group detruyer-rg-production-westeurope-01 --name detruyer-webapp-production-west-europe-01 --src-path ./publish.zip